apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault-kv1

commonLabels:
  app: vault-kv1

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- service-account.yaml
- jobs.yaml
- namespace.yaml
# secretGenerator:
# - name: ca
#   files:
#   - ca.crt.pem
#   type: Opaque

configMapGenerator:
- name: vault-kv1-setup
  files:
  - secret-consumer.hcl
  - vault-k8s-demo-kv1.sh

# generatorOptions:
#   disableNameSuffixHash: true
