apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flask-app

commonLabels:
  apps: flask-app

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- service-account.yaml
- jobs.yaml
- namespace.yaml

images:
- name: flask-app
  newName: registry.gitlab.com/saltydev42/docker-images/flask-app
  newTag: latest

configMapGenerator:
- name: vault-eaas-setup
  files:
  - vault-k8s-demo-transit.sh
  - vault-k8s-demo-transform.sh
  - vault-k8s-eaas.sh
  - flask-app.hcl

