apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterrolebinding.yaml
- service-account.yaml
- jobs.yaml

configMapGenerator:
- name: vault-setup
  files:
  - vault-k8s-demo-setup.sh

secretGenerator:
- name: vault-hclic
  files:
  - vault.hclic
